package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/akhil/gql/database"
	"github.com/akhil/gql/graph/generated"
	"github.com/akhil/gql/graph/model"
)

// CreateCustomerProfile is the resolver for the createCustomerProfile field.
func (r *mutationResolver) CreateCustomerProfile(ctx context.Context, input model.CreateCustomerProfileInput) (*model.CustomerProfile, error) {
	return db.CreateCustomerProfile(input), nil
}

// UpdateCustomerProfile is the resolver for the updateCustomerProfile field.
func (r *mutationResolver) UpdateCustomerProfile(ctx context.Context, id string, input model.UpdateCustomerProfileInput) (*model.CustomerProfile, error) {
	return db.UpdateCustomerProfile(id, input), nil
}

// DeleteCustomerProfile is the resolver for the deleteCustomerProfile field.
func (r *mutationResolver) DeleteCustomerProfile(ctx context.Context, id string) (*model.DeleteCustomerResponse, error) {
	return db.DeleteCustomerProfile(id), nil
}

// Customers is the resolver for the customers field.
func (r *queryResolver) Customers(ctx context.Context) ([]*model.CustomerProfile, error) {
	return db.GetProfiles(), nil
}

// Customer is the resolver for the customer field.
func (r *queryResolver) Customer(ctx context.Context, id string) (*model.CustomerProfile, error) {
	panic(fmt.Errorf("not implemented: Customer - customer"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
var db = database.Connect()

func (r *mutationResolver) CreateJobListing(ctx context.Context, input model.CreateCustomerProfileInput) (*model.CustomerProfile, error) {
	return db.CreateCustomerProfile(input), nil
}
func (r *mutationResolver) UpdateJobListing(ctx context.Context, id string, input model.UpdateCustomerProfileInput) (*model.CustomerProfile, error) {
	return db.UpdateCustomerProfile(id, input), nil
}
func (r *mutationResolver) DeleteJobListing(ctx context.Context, id string) (*model.DeleteCustomerResponse, error) {
	return db.DeleteCustomerProfile(id), nil
}
func (r *queryResolver) Jobs(ctx context.Context) ([]*model.CustomerProfile, error) {
	return db.GetProfiles(), nil
}
func (r *queryResolver) Job(ctx context.Context, id string) (*model.CustomerProfile, error) {
	return db.GetProfile(id), nil
}
